CREATE TABLE IF NOT EXISTS facts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	fact TEXT NOT NULL,
	funny BOOLEAN NOT NULL DEFAULT FALSE,
	ai BOOLEAN NOT NULL DEFAULT FALSE,
  modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS phones (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	phone VARCHAR(20) NOT NULL,
  modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS sent_facts (
	phone_id INT UNSIGNED NOT NULL,
	fact_id INT UNSIGNED NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (phone_id, fact_id)
) ENGINE=INNODB;
