INSERT INTO facts (fact, funny, ai) VALUES 
("Humans started hanging out with goats around 9,000 years ago, making them our original party animals.", 1, 0),
("Worldwide, goat meat is the most consumed meat per capita. That's a lot of goat BBQs!", 1, 0),
("Goats are like A-list celebrities; they respond when you call them by their names.", 1, 0),
("Goats and dogs go paw-in-hoof when it comes to lifespan. Now, if only goats would fetch sticks…", 1, 0),
("Baby goats, or kids, are high-achievers. They start walking immediately after birth.", 1, 0),
("Kids have unique calls and scents, so their moms always know who's who, even in a packed goat nursery.", 1, 0),
("Contrary to popular belief, goats won't eat anything! They have the discerning palate of a gourmet chef.", 1, 0),
("Goats suffer from serious FOMO (fear of missing out) and can get depressed if they don't have any goat buddies to hang out with.", 1, 0),
("Goats are natural-born climbers. If they had thumbs, they’d probably be professional rock climbers.", 1, 0),
("A goat's eyes are like built-in wide-angle lenses with night vision. James Bond has nothing on them!", 1, 0),
("Grazing? Pfft! Goats are foragers, natural foodies looking for the best organic, foraged greens.", 1, 0),
("Goats don't have one, two, or even three stomachs. They have four! Talk about having a big appetite.", 1, 0),
("Goats are master belchers, giving them a competitive edge in any burping contest.", 1, 0),
("\"Kidding\" doesn’t mean telling a joke in the goat world, it’s all about having babies.", 1, 0),
("Goats are tidy eaters, they wouldn't dare to eat off the floor!", 1, 0),
("Goats are the Einsteins of the farm, they're intelligent, curious, and great problem solvers.", 1, 0),
("Goats communicate by bleating. So next time you hear a goat, it might be saying, \"How's your day going?\" in goat language.", 1, 0),
("Goats sneeze to alert others about danger. No, they're not allergic to hay!", 1, 0),
("Goats have a \"no puddles\" policy. They'd rather jump over a puddle than step in it.", 1, 0),
("There are over 200 different goat breeds. It's like nature's own goat fashion show!", 1, 0),
("Some goats are born to be fluffy fashion models, like the Angora goat and its mohair.", 1, 0),
("Some goats are all ears. Nubian or Boer goats have long, floppy ears, perfect for hearing gossip from across the field.", 1, 0),
("Fainting goats don't faint; they just play freeze tag a little too seriously.", 1, 0),
("Coffee might have been discovered by a hyperactive goat who partied all night after eating some mysterious berries.", 1, 0),
("Goats don't like eating dirty food. They'd probably ask for a five-star restaurant if they could.", 1, 0),
("Goats are social butterflies. They love hanging out with their buddies and can tell when humans are happy or grumpy.", 1, 0),
("Goats have rectangular pupils, which might explain why they're so good at eyeing up the best food.", 1, 0),
("Goats can recognize their kids by their calls. They probably never mix up their kids' names like human parents do!", 1, 0),
("Beards are not just for hipsters; goats of both genders can rock a good goatee.", 1, 0),
("Goats can’t chew with their top front teeth because they don't have any! Just a strong dental pad to grind their food.", 1, 0),
("Goats are the Cirque du Soleil performers of the animal kingdom with their excellent balance and climbing skills.", 1, 0),
("If goats had a nation, it would be China - they have over 170 million goat citizens.", 1, 0),
("Goats were among the first immigrants to America, brought over on the Mayflower.", 1, 0),
("Goats are versatile. Their skins have been used as water bottles, for writing parchment, and even as hipster satchels.", 1, 0),
("Goat farming has many purposes: wool for your favorite sweater, milk for your cheese, and meat for your tacos.", 1, 0),
("Goats are distant cousins to cows and antelopes.", 1, 0),
("Goat's milk is the favorite milk worldwide. Cows, you've got some competition!", 1, 0),
("Goat meat is the lean, mean, low-fat alternative to beef, pork, and poultry.", 1, 0),
("Lovebirds have nothing on goats; they have a seasonal breeding period typically from late August to early January.", 1, 0),
("Texas, Tennessee, Georgia, Oklahoma, and Kentucky are the goat-meat capitals of the USA.", 1, 0),
("For all you cheese lovers, Texas, California, Wisconsin, Iowa, and New York are the biggest goat dairy producers.", 1, 0),
("Goat meat industry is growing in the U.S, someone's got to feed the goat-meat craving populace!", 1, 0),
("Goats are smarter than they look. They are great problem-solvers and can learn new tricks by watching others.", 1, 0),
("Goats are the fashion designers' pet, their skins are turned into leather and their pelts made into fancy rugs and robes.", 1, 0),
("A goat's emotional intelligence is off the charts. They can tell when you're having a bad day and prefer to hang with the happy humans.", 1, 0),
("Goats have their own unique language, known as bleating. If only we had a goat-to-English dictionary…", 1, 0),
("Goats love playtime as much as kids. Especially when it involves climbing or hopping onto their caregivers' backs.", 1, 0),
("Goat herds have a pecking order, complete with a \"top buck\" and a \"herd queen.\" It's like high school all over again.", 1, 0),
("Goats take cleanliness seriously. They love a good grooming session and mothers bond with their young by giving them a spa-like bath.", 1, 0),
("In the game of hide-and-seek, goats are winners. They are notably adept at figuring out how to open gates and reach hard-to-reach food.", 1, 0),
("Goats have an uncanny ability to withstand harsh climates, from the blistering heat of the desert to freezing mountain tops. They're basically the ultimate survivalists!", 0, 1),
("Goats have been associated with mythology and symbolism in various cultures. In Norse mythology, Thor had a chariot that was pulled by goats.", 0, 1),
("Can you believe goats can climb trees? In Morocco, they climb Argan trees for their fruit. Someone needs to tell them they're not birds!", 0, 1),
("Goats were one of the first animals to be tamed by humans. They're like the old friends we've had since the Stone Age.", 0, 1),
("The largest goat breed is the Boer goat, and these big guys can weigh up to 300 pounds. That's a whole lot of goat!", 0, 1),
("A group of goats is called a tribe or a trip. Forget road trips, it's time for goat trips!", 0, 1),
("Goat meat has many names depending on how old the goat was when it was butchered. Ever heard of chevon or cabrito?", 0, 1),
("Ever seen a goat with spiral horns? Meet the Markhor, the national animal of Pakistan. Their horns can grow up to 5 feet long!", 0, 1),
("Goats have something called a \"rumen,\" a special stomach compartment for fermenting plant material. They're like walking, bleating bio-fermenters.", 0, 1),
("Goats are naturally immune to many diseases that affect humans. If only we could borrow their immune systems…", 0, 1),
("The world record for the largest number of kids born to one goat in her lifetime is 37! Talk about a big family.", 0, 1),
("Goats played a role in World War II. Coastguards used to use them to clear out undergrowth on the coasts of Britain.", 0, 1),
("The color of a goat's coat can range dramatically, from pure white to dark chocolate and everything in between. They're the natural trendsetters of the farmyard.", 0, 1),
("Ever seen a goat with an underbite? This is totally normal for them. Their bottom jaw extends past their upper jaw to help them grind down tough plant matter.", 0, 1),
("Did you know that goat pupils are horizontal? This allows them to have a nearly 340-degree field of vision.", 0, 1),
("Goats are good swimmers! It's not their favorite activity, but they can swim if necessary. Aquagoat, anyone?", 0, 1),
("There's even a goat sport called \"goat racing,\" which is popular in certain parts of the world.", 0, 1),
("Some goats can produce silk. The Capra hircus, a type of goat, produces a rare type of silk called Pashmina.", 0, 1),
("Some goats, like the Nigerian Dwarf Goat, are great at producing milk despite their small size. Size isn't everything!", 0, 1),
("The famous 'Three Billy Goats Gruff' fairy tale has its origins in Norway, where it was first published in the early 1840s.", 0, 1),
("If you thought goats couldn't get any cooler, they've been launched into space! In 1985, French space agency CNES sent a goat kid along with nine other animals on a trip outside of Earth's atmosphere.", 0, 1),
("Have you ever thought about a goat as a caddie? A golf course in Oregon employs trained goats as golf bag carriers.", 0, 1),
("Certain breeds of goats, like the Australian rangeland goat, have been known to go feral. That's right, wild, free-roaming goats!", 0, 1),
("Goats can form friendships with each other and even have best friends. That's some serious \"bleat\"-bff goals right there.", 0, 1),
("Goat's milk is naturally homogenized. This means the cream remains suspended in the milk rather than rising to the top, like cow's milk.", 0, 1),
("Some goats have been known to share pastures peacefully with other animals, even ones you wouldn't expect like deer.", 0, 1),
("Think you can outrun a goat? Think again! Goats can reach speeds up to 15 miles per hour.", 0, 1),
("It might sound funny, but a goat's bleat has its own accent! Goats from the same area tend to sound similar.", 0, 1),
("Ever seen a goat with a really long beard? That's a \"goatee\" and only male goats (bucks) grow them.", 0, 1),
("Goats don't have teeth on their upper front jaw. They have a hard \"dental pad\" there instead.", 0, 1),
("Goats played a part in the discovery of coffee! Legend has it that an Ethiopian goat herder noticed his goats became energetic after eating berries from a specific tree - coffee berries.", 0, 1),
("The phrase \"getting your goat\" has origins in horse racing. People used to put goats in with nervous racehorses to keep them calm. Removing the goat before a race would unsettle the horse, giving the owner's opponent an advantage.", 0, 1),
("A goat's eyes can protect themselves from dust and bright sunlight. This is due to the positioning and shape of their eyes.", 0, 1),
("A certain breed of goat, the Pygmy Goat, is often kept as a pet because of its good-natured and friendly temperament.", 0, 1),
("Finally, goats have a legendary status in many cultures. In Greek mythology, the god Pan had the legs and horns of a goat!", 0, 1),
("Humans began taming goats around 9,000 years ago, making them one of the first domesticated animals.", 0, 0),
("Worldwide, goat meat stands as the most consumed meat per capita.", 0, 0),
("Impressively, goats can learn and respond to their names when called.", 0, 0),
("Much like dogs, goats usually have a similar life span.", 0, 0),
("A goat's pregnancy lasts five months, yielding an average of 2.2 kids per year.", 0, 0),
("Immediately after birth, baby goats, known as kids, are capable of standing and taking their first steps.", 0, 0),
("Every kid has a unique call and scent, enabling its mother to recognize it from birth, rather than by sight.", 0, 0),
("Goats are discerning eaters, contrary to the stereotype that they'll eat anything. They utilize their sensitive lips to find clean and tasty food, often refusing to eat hay that's been disturbed or left lying for a day.", 0, 0),
("Goats are herd animals and can become depressed without goat companions, suggesting it's unhealthy for a family to keep just one goat as a pet.", 0, 0),
("Climbing skills come naturally to goats, with some observed ascending trees or even dams!", 0, 0),
("A goat's rectangular pupils provide a wide field of vision—320 to 340 degrees—around its body without needing to move. They are believed to have exceptional night vision.", 0, 0),
("Rather than being grazers, goats are foragers. Grazing goats on grass is unnatural and increases the risk of them contracting harmful parasites.", 0, 0),
("Goats possess four \"stomachs.\" Food moves from the rumen (where it's occasionally regurgitated for further \"cud chewing\") to the reticulum, then the omasum, and finally to the abomasum, most similar to a human stomach.", 0, 0),
("Burping is a regular habit for goats, owing to the fermentation process in their rumen, which is capable of holding four to five gallons of plant material.", 0, 0),
("\"Kidding\" refers to a goat giving birth.", 0, 0),
("Goats are selective eaters, cleaner than cows, sheep, pigs, swine, and even dogs.", 0, 0),
("They possess a high level of intelligence and curiosity, often exploring and investigating anything unfamiliar in their environment.", 0, 0),
("Bleating serves as their primary means of communication, with mothers frequently calling their kids to keep them close.", 0, 0),
("Goats emit a sneeze sound as an alarm signal to warn each other of potential danger.", 0, 0),
("They prefer to avoid water, often leaping over streams and puddles instead of stepping in them.", 0, 0),
("With over 200 different goat breeds, size varies greatly. For instance, the Nigerian dwarf goat weighs up to 75 pounds, while the Nubian goat can reach up to 250 pounds.", 0, 0),
("Some goats are fluffy, like the Angora goat, renowned for its soft, long curly hair, known as mohair.", 0, 0),
("Ear size differs among breeds. Nubian or Boer goats possess long, floppy ears, while Lamancha goats have much smaller ears.", 0, 0),
("Myotonic goats, also known as \"fainting\" goats, do not actually faint. Their muscles freeze up when they're frightened, causing them to fall over. However, they remain conscious, and their muscles quickly return to normal.", 0, 0),
("An Ethiopian goat herder reputedly discovered coffee after noticing his goats were energized and wouldn't sleep at night after consuming berries from a specific tree.", 0, 0),
("Female goats are called does or nannies, while males are known as bucks or billies. Kids are baby goats, and when a doe gives birth, it's referred to as kidding.", 0, 0),
("Goats have a preference for clean, rich food, unlike the stereotype of them eating just about anything.", 0, 0),
("Living in herds, goats are very social animals, interacting with other goats, animals, and humans. They can even differentiate between happy and unhappy humans, preferring the company of the former.", 0, 0),
("Rectangular pupils give goats a wider field of vision than those animals with circular pupils.", 0, 0),
("Mothers and kids recognize each other through distinct bleating calls.", 0, 0),
("Goats, regardless of gender, can have beards. Both male and female goats can also have \"wattles\" - bits of dangling skin from their head or neck.", 0, 0),
("Instead of front teeth in their upper jaw, goats possess a strong, hard dental pad to help them breakdown food.", 0, 0),
("Owing to their ancestry from mountain goats, all domestic goat breeds are excellent climbers with great balance.", 0, 0),
("As of now, the world houses about 450 million goats, with China having over 170 million.", 0, 0),
("They were among the first animals to be domesticated and were even brought over on the Mayflower.", 0, 0),
("Early explorers used goat skins for water and wine bottles, while during biblical times, goat skins were utilized for parchment for writing.", 0, 0),
("Goat farming serves various purposes, including wool, milk, and meat production.", 0, 0),
("Goats have a genetic connection to cows and antelopes.", 0, 0),
("Globally, goat's milk is the most popular milk, even though cow's milk is more common in the U.S.", 0, 0),
("Goat meat contains lower fat and cholesterol compared to beef, pork, and poultry.", 0, 0),
("Goats have a lifespan of 8 to 12 years.", 0, 0),
("Like sheep, goats have a seasonal breeding period, typically from late August to early January.", 0, 0),
("Texas, Tennessee, Georgia, Oklahoma, and Kentucky boast the largest populations of meat goats.", 0, 0),
("Texas, California, Wisconsin, Iowa, and New York have the largest goat dairy herds.", 0, 0),
("The meat goat industry is expanding rapidly in the U.S.", 0, 0),
("Coffee discovery is attributed to goats. Goat herders observed their animals becoming energetic after eating coffee beans.", 0, 0),
("Not only are they skillful mountain climbers, but goats are also intelligent problem-solvers.", 0, 0),
("Goats, as herd animals, are happiest when in company and can become depressed if isolated from their companions.", 0, 0),
("Cleanliness matters to goats. They spend significant time grooming, and mothers bond with their young by giving them a bath.", 0, 0),
("Goats' emotional intelligence is remarkable. Studies indicate they can distinguish human facial expressions and prefer to interact with happy-looking humans.", 0, 0),
("Goats use distinct calls, known as bleating, to communicate and identify each other.", 0, 0),
("Goats cherish playtime. They enjoy climbing and feel secure on high ground. Baby goats often hop onto caregivers' backs or climb onto other animals.", 0, 0),
("In goat herds, a complex social structure is observed. Once a hierarchy is established, a \"top buck\" and a \"herd queen\" take charge of the herd's welfare.", 0, 0),
("As quick learners and natural problem-solvers, goats can learn new skills by observing others. These goal-oriented animals are notably adept at figuring out how to open gates and reach hard-to-reach food.", 0, 0),
("Goats form a significant part of the economy in many parts of the world. Their skins are used for leather, and their pelts are made into rugs and robes.", 0, 0);